# Generated by Django 2.1.2 on 2021-01-04 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heyurl', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='click',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='click',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click', to='heyurl.Url'),
        ),
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date updated'),
        ),
    ]
